# Stage 1
FROM node:lts AS build
WORKDIR /usr/src/app
COPY package*.json ./
COPY tsconfig.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2
FROM node:lts
WORKDIR /usr/src/app
COPY --from=build /usr/src/app/dist ./dist
COPY package*.json ./
RUN npm ci --only=production
EXPOSE 4000
CMD [ "node", "./dist/src/server.js"]